vim :: 7.3.081 ;; revamp default vimrc
Signed-off-by: BlackEagle <ike.devolder@gmail.com>

diff --git a/herecura-stable/vim/PKGBUILD b/herecura-stable/vim/PKGBUILD
--- a/herecura-stable/vim/PKGBUILD
+++ b/herecura-stable/vim/PKGBUILD
@@ -1,4 +1,3 @@
-# vim:set sw=2 sts=2 et:
 # Maintainer: BlackEagle < ike DOT devolder AT gmail DOT com >
 # thx for the original vim pkg:
 # Contributor: Jan "heftig" Steffens <jan.steffens@gmail.com>
@@ -11,24 +10,24 @@ _basever=7.3
 _patchlevel=081
 pkgver=${_basever}.${_patchlevel}
 __hgrev=916c90b37e
-pkgrel=2
+pkgrel=3
 _versiondir=vim${_basever/./}
 arch=('i686' 'x86_64')
 license=('custom:vim')
 url="http://www.vim.org"
 makedepends=('gpm' 'perl' 'python2' 'ruby' 'lua' 'libxt' 'desktop-file-utils' 'gtk2'
-             'gettext' 'pkgconfig' 'sed' 'mercurial')
+	'gettext' 'pkgconfig' 'sed' 'mercurial')
 options=()
 source=(
-  'vimrc'
-  'archlinux.vim'
-  'gvim.desktop'
-  'license.txt'
+	'vimrc'
+	'peaksea.vim'
+	'gvim.desktop'
+	'license.txt'
 )
-sha256sums=('70623e05d612985c76048ee26cc3daf746bb0becf179bd33c976eb549ebb2399'
-            'c4fe5e30dfd5093353e42c2c514d4492bec64da17f9a2b4e306af6ee39320715'
-            '5f2d65e755424f688b990b20bce6bd84718b9d5f7944a5332b5dee72f09493f7'
-            'bb4744930a0030085d382356e9fdd4f2049b6298147aee2470c7fca7ec82fd55')
+sha256sums=('76cb80e89fcd121069ed84ba06392e507784720d83aaa0c1509570f3bc8818ba'
+	'0e6a2364c9fe45169efc68b3f301c3965e9202b67fd37fe1b93c7e3060887fdf'
+	'5f2d65e755424f688b990b20bce6bd84718b9d5f7944a5332b5dee72f09493f7'
+	'bb4744930a0030085d382356e9fdd4f2049b6298147aee2470c7fca7ec82fd55')
 
 __hgroot='http://vim.googlecode.com/hg/'
 __hgrepo='vim'
@@ -37,209 +36,210 @@ __hgbranch='default'
 ##### Build #####
 
 build() {
-  [ -d vim-build ] && rm -rf vim-build
-  [ -d gvim-build ] && rm -rf gvim-build
-  [ -d vim-sl-build ] && rm -rf vim-sl-build
-  msg2 'Checking out source from Mercurial...'
+	[ -d vim-build ] && rm -rf vim-build
+	[ -d gvim-build ] && rm -rf gvim-build
+	[ -d vim-sl-build ] && rm -rf vim-sl-build
+	msg2 'Checking out source from Mercurial...'
 
-  if [[ -d ${__hgrepo} ]]; then
-    cd ${__hgrepo}
-    hg pull -b ${__hgbranch}|| warning 'hg pull failed!'
-    hg update -r ${__hgrev}
-    cd ${srcdir}
-  else
-    hg clone -b ${__hgbranch} -u ${__hgrev} "${__hgroot}${__hgrepo}" ${__hgrepo}
-  fi
+	if [[ -d ${__hgrepo} ]]; then
+		cd ${__hgrepo}
+		hg pull -b ${__hgbranch}|| warning 'hg pull failed!'
+		hg update -r ${__hgrev}
+		cd ${srcdir}
+	else
+		hg clone -b ${__hgbranch} -u ${__hgrev} "${__hgroot}${__hgrepo}" ${__hgrepo}
+	fi
 
-  cp -a ${pkgbase} vim-build
-  (cd vim-build && rm -rf ./.hg)
+	cp -a ${pkgbase} vim-build
+	(cd vim-build && rm -rf ./.hg)
 
-  # define the place for the global (g)vimrc file (set to /etc/vimrc)
-  sed -i 's|^.*\(#define SYS_.*VIMRC_FILE.*"\) .*$|\1|' \
-    vim-build/src/feature.h
-  sed -i 's|^.*\(#define VIMRC_FILE.*"\) .*$|\1|' \
-    vim-build/src/feature.h
-  # fix python name
-  sed -i -e 's|vi_cv_path_python, python|vi_cv_path_python, python2|' \
-    vim-build/src/configure.in
-  (cd vim-build/src && autoconf)
+	# define the place for the global (g)vimrc file (set to /etc/vimrc)
+	sed -i 's|^.*\(#define SYS_.*VIMRC_FILE.*"\) .*$|\1|' \
+		vim-build/src/feature.h
+	sed -i 's|^.*\(#define VIMRC_FILE.*"\) .*$|\1|' \
+		vim-build/src/feature.h
+	# fix python name
+	sed -i -e 's|vi_cv_path_python, python|vi_cv_path_python, python2|' \
+		vim-build/src/configure.in
+	(cd vim-build/src && autoconf)
 
-  msg2 'Building...'
+	msg2 'Building...'
 
-  cp -a vim-build gvim-build
-  cp -a vim-build vim-sl-build
+	cp -a vim-build gvim-build
+	cp -a vim-build vim-sl-build
 
-  msg2 'Building vim-slim'
-  cd ${srcdir}/vim-sl-build
-  ./configure --prefix=/usr --localstatedir=/var/lib/vim \
-    --mandir=/usr/share/man --with-compiledby=ArchLinux \
-    --with-features=tiny --disable-gpm --enable-acl --with-x=no \
-    --disable-gui --enable-multibyte --disable-cscope \
-    --disable-netbeans --disable-perlinterp --disable-pythoninterp \
-    --disable-rubyinterp --enable-luainterp=no
-  make
+	msg2 'Building vim-slim'
+	cd ${srcdir}/vim-sl-build
+	./configure --prefix=/usr --localstatedir=/var/lib/vim \
+		--mandir=/usr/share/man --with-compiledby=ArchLinux \
+		--with-features=tiny --disable-gpm --enable-acl --with-x=no \
+		--disable-gui --enable-multibyte --disable-cscope \
+		--disable-netbeans --disable-perlinterp --disable-pythoninterp \
+		--disable-rubyinterp --enable-luainterp=no
+	make
 
-  msg2 'Building vim-cli'
-  cd ${srcdir}/vim-build
-  ./configure --prefix=/usr --localstatedir=/var/lib/vim \
-    --mandir=/usr/share/man --with-compiledby=ArchLinux \
-    --with-features=huge --enable-gpm --enable-acl --with-x=no \
-    --disable-gui --enable-multibyte --enable-cscope \
-    --disable-netbeans --enable-perlinterp --enable-pythoninterp \
-    --enable-rubyinterp --enable-luainterp=yes
-  make
+	msg2 'Building vim-cli'
+	cd ${srcdir}/vim-build
+	./configure --prefix=/usr --localstatedir=/var/lib/vim \
+		--mandir=/usr/share/man --with-compiledby=ArchLinux \
+		--with-features=huge --enable-gpm --enable-acl --with-x=no \
+		--disable-gui --enable-multibyte --enable-cscope \
+		--disable-netbeans --enable-perlinterp --enable-pythoninterp \
+		--enable-rubyinterp --enable-luainterp=yes
+	make
 
-  msg2 'Building vim-gvim'
-  cd ${srcdir}/gvim-build
-  ./configure --prefix=/usr --localstatedir=/var/lib/vim \
-    --mandir=/usr/share/man --with-compiledby=ArchLinux \
-    --with-features=huge --enable-gpm --enable-acl --with-x=yes \
-    --enable-gui=gtk2 --enable-multibyte --enable-cscope \
-    --enable-netbeans --enable-perlinterp --enable-pythoninterp \
-    --enable-rubyinterp --enable-luainterp=yes
-  make
+	msg2 'Building vim-gvim'
+	cd ${srcdir}/gvim-build
+	./configure --prefix=/usr --localstatedir=/var/lib/vim \
+		--mandir=/usr/share/man --with-compiledby=ArchLinux \
+		--with-features=huge --enable-gpm --enable-acl --with-x=yes \
+		--enable-gui=gtk2 --enable-multibyte --enable-cscope \
+		--enable-netbeans --enable-perlinterp --enable-pythoninterp \
+		--enable-rubyinterp --enable-luainterp=yes
+	make
 }
 
 ##### Packaging #####
 
 package_vim-slim() {
-  pkgdesc='Vi Improved, a highly configurable, improved version of the vi text editor, slim edition'
-  conflicts=('vim' 'vim-cli')
-  provides=('vim')
+pkgdesc='Vi Improved, a highly configurable, improved version of the vi text editor, slim edition'
+conflicts=('vim' 'vim-cli')
+provides=('vim')
 
-  cd ${srcdir}/vim-sl-build
-  make -j1 VIMRCLOC=/etc DESTDIR=${pkgdir} install
+cd ${srcdir}/vim-sl-build
+make -j1 VIMRCLOC=/etc DESTDIR=${pkgdir} install
 
-  # provided by (n)vi in core
-  rm ${pkgdir}/usr/bin/{ex,view}
+# provided by (n)vi in core
+rm ${pkgdir}/usr/bin/{ex,view}
 
-  # delete some manpages
-  find ${pkgdir}/usr/share/man -type d -name 'man1' 2>/dev/null | \
-    while read _mandir; do
-    cd ${_mandir}
-    rm -f ex.1 view.1 # provided by (n)vi
-    rm -f evim.1    # this does not make sense if we have no GUI
-  done
+# delete some manpages
+find ${pkgdir}/usr/share/man -type d -name 'man1' 2>/dev/null | \
+	while read _mandir; do
+		cd ${_mandir}
+		rm -f ex.1 view.1 # provided by (n)vi
+		rm -f evim.1    # this does not make sense if we have no GUI
+	done
 
-  # Runtime provided by runtime package
-  rm -r ${pkgdir}/usr/share/vim
+	# Runtime provided by runtime package
+	rm -r ${pkgdir}/usr/share/vim
 
-  # license
-  install -dm755 ${pkgdir}/usr/share/licenses/vim-slim
-  install -Dm644 ${srcdir}/license.txt \
-    ${pkgdir}/usr/share/licenses/vim-slim/license.txt
+	# license
+	install -dm755 ${pkgdir}/usr/share/licenses/vim-slim
+	install -Dm644 ${srcdir}/license.txt \
+		${pkgdir}/usr/share/licenses/vim-slim/license.txt
 }
 
 package_vim-cli() {
-  pkgdesc='Vi Improved, a highly configurable, improved version of the vi text editor, cli only'
-  depends=("vim-rt=${pkgver}-${pkgrel}" 'gpm' 'perl' 'python2' 'ruby' 'lua')
-  conflicts=('vim' 'vim-slim')
-  provides=('vim')
+pkgdesc='Vi Improved, a highly configurable, improved version of the vi text editor, cli only'
+depends=("vim-rt=${pkgver}-${pkgrel}" 'gpm' 'perl' 'python2' 'ruby' 'lua')
+conflicts=('vim' 'vim-slim')
+provides=('vim')
 
-  cd ${srcdir}/vim-build
-  make -j1 VIMRCLOC=/etc DESTDIR=${pkgdir} install
+cd ${srcdir}/vim-build
+make -j1 VIMRCLOC=/etc DESTDIR=${pkgdir} install
 
-  # provided by (n)vi in core
-  rm ${pkgdir}/usr/bin/{ex,view}
+# provided by (n)vi in core
+rm ${pkgdir}/usr/bin/{ex,view}
 
-  # delete some manpages
-  find ${pkgdir}/usr/share/man -type d -name 'man1' 2>/dev/null | \
-    while read _mandir; do
-    cd ${_mandir}
-    rm -f ex.1 view.1 # provided by (n)vi
-    rm -f evim.1    # this does not make sense if we have no GUI
-  done
+# delete some manpages
+find ${pkgdir}/usr/share/man -type d -name 'man1' 2>/dev/null | \
+	while read _mandir; do
+		cd ${_mandir}
+		rm -f ex.1 view.1 # provided by (n)vi
+		rm -f evim.1    # this does not make sense if we have no GUI
+	done
 
-  # Runtime provided by runtime package
-  rm -r ${pkgdir}/usr/share/vim
+	# Runtime provided by runtime package
+	rm -r ${pkgdir}/usr/share/vim
 
-  # license
-  install -dm755 ${pkgdir}/usr/share/licenses/vim-cli
-  install -Dm644 ${srcdir}/license.txt \
-    ${pkgdir}/usr/share/licenses/vim-cli/license.txt
+	# license
+	install -dm755 ${pkgdir}/usr/share/licenses/vim-cli
+	install -Dm644 ${srcdir}/license.txt \
+		${pkgdir}/usr/share/licenses/vim-cli/license.txt
 }
 
 package_vim-gvim() {
-  pkgdesc='Vi Improved, a highly configurable, improved version of the vi text editor (with advanced features, such as a GUI)'
-  depends=('vim-cli' 'libxt' 'desktop-file-utils' 'gtk2')
-  provides=("vim=${pkgver}-${pkgrel}")
-  conflicts=('gvim')
-  provides=('gvim')
-  install=gvim.install
+pkgdesc='Vi Improved, a highly configurable, improved version of the vi text editor (with advanced features, such as a GUI)'
+depends=('vim-cli' 'libxt' 'desktop-file-utils' 'gtk2')
+provides=("vim=${pkgver}-${pkgrel}")
+conflicts=('gvim')
+provides=('gvim')
+install=gvim.install
 
-  cd ${srcdir}/gvim-build
-  make -j1 VIMRCLOC=/etc DESTDIR=${pkgdir} install
+cd ${srcdir}/gvim-build
+make -j1 VIMRCLOC=/etc DESTDIR=${pkgdir} install
 
-  # provided by (n)vi in core
-  rm ${pkgdir}/usr/bin/{ex,view}
+# provided by (n)vi in core
+rm ${pkgdir}/usr/bin/{ex,view}
 
-  # cleanup so there is no more conflict with vim-bin
-  cd ${pkgdir}/usr/bin/
-  mv vim gvim
-  rm -f rview rvim vimdiff vimtutor xxd # all available in vim-bin
-  rm -f eview evim gview gvimdiff rgview rgvim # symlinking to vim, has to be gvim
-  ln -s gvim eview
-  ln -s gvim evim
-  ln -s gvim gview
-  ln -s gvim gvimdiff
-  ln -s gvim rgview
-  ln -s gvim rgvim
+# cleanup so there is no more conflict with vim-bin
+cd ${pkgdir}/usr/bin/
+mv vim gvim
+rm -f rview rvim vimdiff vimtutor xxd # all available in vim-bin
+rm -f eview evim gview gvimdiff rgview rgvim # symlinking to vim, has to be gvim
+ln -s gvim eview
+ln -s gvim evim
+ln -s gvim gview
+ln -s gvim gvimdiff
+ln -s gvim rgview
+ln -s gvim rgvim
 
-  cd ${srcdir}/gvim-build
+cd ${srcdir}/gvim-build
 
-  # delete some manpages
-  find ${pkgdir}/usr/share/man -type d -name 'man1' 2>/dev/null | \
-    while read _mandir; do
-    cd ${_mandir}
-    rm -f ex.1 view.1 # provided by (n)vi
-    rm -f rview.1 rvim.1 vim.1 vimdiff.1 vimtutor.1 xxd.1 # provided by vim-bin
-  done
+# delete some manpages
+find ${pkgdir}/usr/share/man -type d -name 'man1' 2>/dev/null | \
+	while read _mandir; do
+		cd ${_mandir}
+		rm -f ex.1 view.1 # provided by (n)vi
+		rm -f rview.1 rvim.1 vim.1 vimdiff.1 vimtutor.1 xxd.1 # provided by vim-bin
+	done
 
-  # Move the runtime for later packaging
-  mv ${pkgdir}/usr/share/vim ${srcdir}/runtime-install
+	# Move the runtime for later packaging
+	mv ${pkgdir}/usr/share/vim ${srcdir}/runtime-install
 
-  # freedesktop links
-  install -Dm644 ${srcdir}/gvim.desktop \
-    ${pkgdir}/usr/share/applications/gvim.desktop
-  install -Dm644 runtime/vim48x48.png ${pkgdir}/usr/share/pixmaps/gvim.png
+	# freedesktop links
+	install -Dm644 ${srcdir}/gvim.desktop \
+		${pkgdir}/usr/share/applications/gvim.desktop
+	install -Dm644 runtime/vim48x48.png ${pkgdir}/usr/share/pixmaps/gvim.png
 
-  # license
-  install -dm755 ${pkgdir}/usr/share/licenses/vim-gvim
-  install -Dm644 ${srcdir}/license.txt \
-    ${pkgdir}/usr/share/licenses/vim-gvim/license.txt
+	# license
+	install -dm755 ${pkgdir}/usr/share/licenses/vim-gvim
+	install -Dm644 ${srcdir}/license.txt \
+		${pkgdir}/usr/share/licenses/vim-gvim/license.txt
 }
 
 package_vim-rt() {
-  pkgdesc='Runtime for vim and gvim'
-  conflicts=('vim-runtime')
-  provides=('vim-runtime')
-  backup=(etc/vimrc)
+pkgdesc='Runtime for vim and gvim'
+conflicts=('vim-runtime')
+provides=('vim-runtime')
+backup=(etc/vimrc)
 
-  # Install the runtime split from gvim
-  install -dm755 ${pkgdir}/usr/share
-  mv ${srcdir}/runtime-install ${pkgdir}/usr/share/vim
+# Install the runtime split from gvim
+install -dm755 ${pkgdir}/usr/share
+mv ${srcdir}/runtime-install ${pkgdir}/usr/share/vim
 
-  # Don't forget logtalk.dict
-  install -Dm644 ${srcdir}/gvim-build/runtime/ftplugin/logtalk.dict \
-    ${pkgdir}/usr/share/vim/${_versiondir}/ftplugin/logtalk.dict
+# Don't forget logtalk.dict
+install -Dm644 ${srcdir}/gvim-build/runtime/ftplugin/logtalk.dict \
+	${pkgdir}/usr/share/vim/${_versiondir}/ftplugin/logtalk.dict
 
-  # fix FS#17216
-  sed -i 's|messages,/var|messages,/var/log/messages.log,/var|' \
-    ${pkgdir}/usr/share/vim/${_versiondir}/filetype.vim
+# fix FS#17216
+sed -i 's|messages,/var|messages,/var/log/messages.log,/var|' \
+	${pkgdir}/usr/share/vim/${_versiondir}/filetype.vim
 
-  # patch filetype.vim for better handling of pacman related files
-  sed -i "s/rpmsave/pacsave/;s/rpmnew/pacnew/;s/,\*\.ebuild/\0,PKGBUILD*,*.install/" \
-    ${pkgdir}/usr/share/vim/${_versiondir}/filetype.vim
-  sed -i "/find the end/,+3{s/changelog_date_entry_search/changelog_date_end_entry_search/}" \
-    ${pkgdir}/usr/share/vim/${_versiondir}/ftplugin/changelog.vim
+# patch filetype.vim for better handling of pacman related files
+sed -i "s/rpmsave/pacsave/;s/rpmnew/pacnew/;s/,\*\.ebuild/\0,PKGBUILD*,*.install/" \
+	${pkgdir}/usr/share/vim/${_versiondir}/filetype.vim
+sed -i "/find the end/,+3{s/changelog_date_entry_search/changelog_date_end_entry_search/}" \
+	${pkgdir}/usr/share/vim/${_versiondir}/ftplugin/changelog.vim
 
-  # rc files
-  install -Dm644 ${srcdir}/vimrc ${pkgdir}/etc/vimrc
-  install -Dm644 ${srcdir}/archlinux.vim \
-    ${pkgdir}/usr/share/vim/vimfiles/archlinux.vim
+# rc files
+install -Dm644 ${srcdir}/vimrc ${pkgdir}/etc/vimrc
+install -dm755 ${pkgdir}/usr/share/vim/vimfiles/colors
+install -Dm644 ${srcdir}/peaksea.vim \
+	${pkgdir}/usr/share/vim/vimfiles/colors/peaksea.vim
 
-  # license
-  install -dm755 ${pkgdir}/usr/share/licenses/vim-rt
-  install -Dm644 ${srcdir}/license.txt \
-    ${pkgdir}/usr/share/licenses/vim-rt/license.txt
+# license
+install -dm755 ${pkgdir}/usr/share/licenses/vim-rt
+install -Dm644 ${srcdir}/license.txt \
+	${pkgdir}/usr/share/licenses/vim-rt/license.txt
 }
